#### general settings
name: ESRGAN_DIV_none_20
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
niqe: true

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ../../datasets/DIV2K_train_bicLRx4/HR/x4.lmdb
    dataroot_LQ: ../../datasets/DIV2K_train_bicLRx4/LR/x4.lmdb
#    name: BSD
#    mode: LQGT
#    dataroot_GT: ../../datasets/BSDS_train_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: ../../datasets/BSDS_train_bicLRx4/LR/x4.lmdb
#    name: urban100
#    mode: LQGT
#    dataroot_GT: ../../datasets/urban100_train_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: ../../datasets/urban100_train_bicLRx4/LR/x4.lmdb

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K_val
    mode: LQGT
    dataroot_GT: ../../datasets/DIV2K_valid_bicLRx4/HR/x4.lmdb
    dataroot_LQ: ../../datasets/DIV2K_valid_bicLRx4/LR/x4.lmdb
#    name: BSD_val
#    mode: LQGT
#    dataroot_GT: ../../datasets/BSDS_valid_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: ../../datasets/BSDS_valid_bicLRx4/LR/x4.lmdb
#    name: urban100
#    mode: LQGT
#    dataroot_GT: ../../python/datasets/urban100_test_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: ../../datasets/urban100_test_bicLRx4/LR/x4.lmdb
    batch_size: 16

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 20
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 4

#### path
path:
  pretrain_model_G: /home/teven/canvas/python/BasicSR/experiments/ESRGAN_DIV_none_20/models/1_G.pth
  pretrain_model_D: /home/teven/canvas/python/BasicSR/experiments/ESRGAN_DIV_none_20/models/1_D.pth
#  pretrain_model_G: null
  strict_load: true
  resume_state: /home/teven/canvas/python/BasicSR/experiments/ESRGAN_DIV_none_20/training_state/1.state

#### training settings: learning rate scheme, loss
train:
  G_pretraining: 0
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR
  lr_decay: 0.2
  min_lr: !!float 1e-5

  nepochs: 1000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5
  epoch_patience: 3
  accumulate: 2

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 1e0

#### logger
logger:
  print_freq: !!float 1e0