#### general settings
name: ReacDiff_test
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [0]
niqe: false

#### datasets
datasets:
  train:
#    name: DIV2K
#    mode: LQGT
#    dataroot_GT: /home/teven/canvas/python/datasets/DIV2K_train_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: /home/teven/canvas/python/datasets/DIV2K_train_bicLRx4/LR/x4.lmdb
    name: BSD
    mode: LQGT
    dataroot_GT: /home/teven/canvas/python/datasets/BSDS_train_bicLRx4/HR/x4.lmdb
    dataroot_LQ: /home/teven/canvas/python/datasets/BSDS_train_bicLRx4/LR/x4.lmdb
#    name: urban100
#    mode: LQGT
#    dataroot_GT: /home/teven/canvas/python/datasets/urban100_train_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: /home/teven/canvas/python/datasets/urban100_train_bicLRx4/LR/x4.lmdb

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
#    name: DIV2K_val
#    mode: LQGT
#    dataroot_GT: /home/teven/canvas/python/datasets/DIV2K_valid_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: /home/teven/canvas/python/datasets/DIV2K_valid_bicLRx4/LR/x4.lmdb
    name: BSD_val
    mode: LQGT
    dataroot_GT: /home/teven/canvas/python/datasets/BSDS_valid_bicLRx4/HR/x4.lmdb
    dataroot_LQ: /home/teven/canvas/python/datasets/BSDS_valid_bicLRx4/LR/x4.lmdb
#    name: urban100
#    mode: LQGT
#    dataroot_GT: /home/teven/canvas/python/datasets/urban100_test_bicLRx4/HR/x4.lmdb
#    dataroot_LQ: /home/teven/canvas/python/datasets/urban100_test_bicLRx4/LR/x4.lmdb
    batch_size: 16

#### network structures
network_G:
  which_model_G: ReacDiff
  differential: ~
  in_nc: 3
  out_nc: 3
  nf: 8
  nb: 5

#### path
path:
#  pretrain_model_G: ../experiments/pretrained_models/RRDB_PSNR_x4.pth
  pretrain_model_G: null
  strict_load: true
  resume_state: null

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  lr_decay: 0.2
  min_lr: !!float 1e-5
  nepochs: 50
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7
  epoch_patience: 3
  accumulate: 2

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 1e0

#### logger
logger:
  print_freq: 1